- name: Ubuntu
  hosts: all
  become: true
  roles:
    - role: remove-snap
  tasks:
    - name: Create binary dir
      ansible.builtin.file:
        path: "/test"
        state: directory
        mode: '0755'
