- name: Ubuntu
  hosts: localhost
  connection: local
  become: true
  tasks:

    - name: Create binary dir
      ansible.builtin.file:
        path: "/test"
        state: directory
        mode: '0755'
