- name: Ubuntu
  hosts: all
  become: true
  roles:
    - role: remove_snap
  tasks:
    - name: Create binary dir
      ansible.builtin.file:
        path: "/test"
        state: absent
          # mode: '0755'
