# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
